reference: "inputs/ref.fa"
dark_contigs: "inputs/dark_contigs_condtp.tsv"
highlight_sequences: "inputs/insertion_sequences/flanks.fa"
highlight_intensities: "inputs/insertion_sequences/ancestral_read_fractions.tsv"
assemblies: "inputs/assemblies.tsv"
